name: cicd pipeline

on : [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      - name: install pakages
        run: npm install
      
      - name: test the application
        run: npm run check


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: install node js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      - name: create artifact
        run: |
          mkdir build
          cd build
          echo "DevOps world" > DevOps.txt
        
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_folder
          path: ./build


  deploy:
    needs: build
    runs-on: self-hosted
    steps:

      - name: chekout
        uses: actions/checkout@v3

      - name: receive artifact
        uses: actions/download-artifact@v4
        with:
          name: build_folder
      
      - name: show artifact
        run: |
          ls -a

      - name: install the package
        run: npm install

      - name: run application
        run: |
          ls -a
          pm2 status
          
          #delete node-app process
          pm2 delete node-app || true
          
          #create background process named node-app
          pm2 start "npm start" --name="node-app"

          #save the process
          pm2 save